# Generated by Django 5.2.17 on 2026-09-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operation", "0004_rename_drink_id_drinkingredient_drink_and_more"),
        ("ordering", "0003_rename_shop_id_order_shop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HELD", "Held"),
                            ("CONSUMED", "Consumed"),
                            ("RELEASED", "Released"),
                        ],
                        default="HELD",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to="operation.inventory",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_holds",
                        to="ordering.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Waiting for payment"),
                            ("SUCCEEDED", "Paid"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUND_NEEDED", "Paid, needs refund"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("provider_ref", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="ordering.order",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_ref", ""), _negated=True),
                        fields=("method", "provider_ref"),
                        name="unique_provider_ref_per_method",
                    )
                ],
            },
        ),
    ]
