# Generated by Django 5.2.8 on 2025-12-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Milk Tea'), (2, 'Fruit Tea'), (3, 'Smoothie'), (4, 'Coffee'), (0, 'Others')], default=0),
        ),
        migrations.AddField(
            model_name='drink',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
