# Generated by Django 5.2.8 on 2025-12-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_drink_category_drink_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkingredient',
            old_name='drink',
            new_name='drink_id',
        ),
        migrations.RenameField(
            model_name='drinkingredient',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.AlterUniqueTogether(
            name='drinkingredient',
            unique_together={('drink_id', 'ingredient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('shop_id', 'ingredient_id')},
        ),
    ]
