# Generated by Django 5.2.8 on 2025-12-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_rename_drink_drinkingredient_drink_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkingredient',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='drinkingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='drinkingredient',
            unique_together={('drink', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('shop', 'ingredient')},
        ),
    ]
