# Generated by Django 5.2.17 on 2026-09-25 16:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0004_rename_drink_id_drinkingredient_drink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="drinkingredient",
            name="scaling",
            field=models.SmallIntegerField(
                choices=[(0, "Fixed"), (1, "Sugar level"), (2, "Ice level")], default=0
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="contains_sweetener",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="density_factor",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("1.000"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="exclude_from_grade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="reorder_threshold",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="saturated_fat_per_100",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="sugar_per_100",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="viscosity_rating",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Water-like"),
                    (2, "Low"),
                    (3, "Medium (milk, light syrup)"),
                    (4, "High (thick syrup, puree)"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="last_cip_cleaned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="last_temp_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="max_safe_temp_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="min_safe_temp_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=50, unique=True)),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="OFFLINE",
                        max_length=12,
                    ),
                ),
                ("sfa_locked", models.BooleanField(default=False)),
                ("sfa_lock_reason", models.CharField(blank=True, max_length=200)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiosk",
                        to="operation.shop",
                    ),
                ),
            ],
        ),
    ]
