# Generated by Django 5.2.17 on 2026-09-25 17:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0006_stock_and_temperature_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="code",
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="designer_category",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="designer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="display_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LIQUID", "Liquid"),
                    ("TOPPING", "Topping"),
                    ("OTHER", "Other (ice, sweetener)"),
                ],
                default="LIQUID",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="offered_in_designer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="share",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.CreateModel(
            name="DesignerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cup_price_small",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.80"), max_digits=4
                    ),
                ),
                (
                    "cup_price_large",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.40"), max_digits=4
                    ),
                ),
                (
                    "default_liquid_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.50"), max_digits=4
                    ),
                ),
                (
                    "default_topping_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.60"), max_digits=4
                    ),
                ),
                (
                    "liquid_ml_small",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("360"), max_digits=6
                    ),
                ),
                (
                    "liquid_ml_large",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("500"), max_digits=6
                    ),
                ),
                (
                    "topping_g_small",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("60"), max_digits=6
                    ),
                ),
                (
                    "topping_g_large",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("80"), max_digits=6
                    ),
                ),
                (
                    "sweetener_ml_small",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("30"), max_digits=6
                    ),
                ),
                (
                    "sweetener_ml_large",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("40"), max_digits=6
                    ),
                ),
                (
                    "sweetener",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="operation.ingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "drink designer settings",
                "verbose_name_plural": "drink designer settings",
            },
        ),
    ]
