# Generated by Django 6.1.1 on 2026-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0007_designer"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiosk",
            name="api_key_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
