# Generated by Django 5.2.8 on 2025-12-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_quantity', models.PositiveSmallIntegerField(default=1)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.shop')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField(choices=[(1, 'Large'), (0, 'Small')], default=0)),
                ('sugar', models.SmallIntegerField(choices=[(4, '100%'), (3, '75%'), (2, '50%'), (1, '25%'), (0, '0%')], default=0)),
                ('ice', models.SmallIntegerField(choices=[(4, '100%'), (3, '75%'), (2, '50%'), (1, '25%'), (0, '0%')], default=0)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.drink')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.order')),
            ],
        ),
    ]
