# Generated by Django 5.2.8 on 2025-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='drink',
            new_name='drink_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('TBM', 'To Be Made')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
