# Generated by Django 5.2.8 on 2025-12-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_rename_shop_order_shop_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
