# Generated by Django 5.2.17 on 2026-09-25 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0005_kiosk_nutrigrade"),
        ("ordering", "0003_rename_shop_id_order_shop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_pin",
            field=models.CharField(blank=True, db_index=True, max_length=6),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_token",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="nutri_grade",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="saturated_fat_g_per_100ml",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sugar_g_per_100ml",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.shop"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("TBM", "To Be Made"),
                    ("PAID", "Paid / Ready for Dispense"),
                    ("COLLECTED", "Collected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="drink",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.drink"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="ice",
            field=models.SmallIntegerField(
                choices=[(4, "100%"), (3, "75%"), (2, "50%"), (1, "25%"), (0, "0%")],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sugar",
            field=models.SmallIntegerField(
                choices=[(4, "100%"), (3, "75%"), (2, "50%"), (1, "25%"), (0, "0%")],
                default=4,
            ),
        ),
    ]
