# Generated by Django 5.2.17 on 2026-09-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0007_designer"),
        ("ordering", "0004_kiosk_nutrigrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operation.drink",
            ),
        ),
        migrations.CreateModel(
            name="OrderItemIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operation.ingredient",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_ingredients",
                        to="ordering.orderitem",
                    ),
                ),
            ],
        ),
    ]
