# Generated by Django 6.1.1 on 2026-09-30 17:22

import django.db.models.deletion
from django.db import migrations, models


def retire_old_statuses(apps, schema_editor):
    # TBM ("to be made") stood in for paid before PAID existed; COMPLETED was never used
    Order = apps.get_model("ordering", "Order")
    Order.objects.filter(status="TBM").update(status="PAID")
    Order.objects.filter(status="COMPLETED").update(status="COLLECTED")


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0005_designer"),
    ]

    operations = [
        migrations.RunPython(retire_old_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting for payment"),
                    ("PAID", "Paid"),
                    ("COLLECTED", "Collected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=10)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for payment"),
                            ("PAID", "Paid"),
                            ("COLLECTED", "Collected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=100)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="ordering.order",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "pk"],
            },
        ),
    ]
