# Generated by Django 6.1.1 on 2026-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0006_order_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting for payment"),
                    ("PAID", "Paid"),
                    ("PREPARING", "Being made"),
                    ("READY", "Ready to collect"),
                    ("FAILED", "Couldn't be made"),
                    ("REFUND_NEEDED", "Not made, refund needed"),
                    ("COLLECTED", "Collected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="from_status",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting for payment"),
                    ("PAID", "Paid"),
                    ("PREPARING", "Being made"),
                    ("READY", "Ready to collect"),
                    ("FAILED", "Couldn't be made"),
                    ("REFUND_NEEDED", "Not made, refund needed"),
                    ("COLLECTED", "Collected"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=15,
            ),
        ),
    ]
