"""
Django settings for kiosk_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Everything that differs between a laptop and a real deployment comes from environment
# variables. For local development set DJANGO_DEBUG=1 (./dev.sh does this for you).
DEBUG = os.environ.get('DJANGO_DEBUG', '').lower() in ('1', 'true', 'yes')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'Set DJANGO_SECRET_KEY, or set DJANGO_DEBUG=1 for local development.')
    SECRET_KEY = 'django-insecure-local-development-only'

# comma-separated, e.g. "kiosk.example.com,10.0.0.5"; localhost is allowed when DEBUG is on
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Set DJANGO_HTTPS=1 when the site is served over HTTPS (usually behind a proxy that handles TLS).
# It sends plain-HTTP visitors to HTTPS, keeps cookies HTTPS-only and turns on HSTS.
if os.environ.get('DJANGO_HTTPS', '').lower() in ('1', 'true', 'yes'):
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # start short; raise it (e.g. to 31536000, one year) once HTTPS is known to work everywhere
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '3600'))
    # the proxy in front says whether the visitor used HTTPS; without this the redirect would loop
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HSTS for subdomains and the browser preload list depend on the company's domain, so they are
# left off; set SECURE_HSTS_INCLUDE_SUBDOMAINS / SECURE_HSTS_PRELOAD here once that is decided.
SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W021']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'ordering',
    'checkout',
    'rest_framework',
    'operation'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kiosk_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiosk_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# The PayNow account order QR codes pay (payments/paynow.py). These are company credentials, so
# they only come from the environment. In development a dummy UEN is used so the QR screen works;
# without DEBUG, the QR endpoint refuses to make codes until PAYNOW_PROXY_VALUE is set.
PAYNOW_PROXY_TYPE = os.environ.get('PAYNOW_PROXY_TYPE', 'UEN')  # UEN or MOBILE
PAYNOW_PROXY_VALUE = os.environ.get('PAYNOW_PROXY_VALUE', '000000000X' if DEBUG else '')
PAYNOW_MERCHANT_NAME = os.environ.get('PAYNOW_MERCHANT_NAME', 'Drink Shop Kiosk')
PAYNOW_MERCHANT_CITY = os.environ.get('PAYNOW_MERCHANT_CITY', 'Singapore')
PAYNOW_MERCHANT_CATEGORY_CODE = os.environ.get('PAYNOW_MERCHANT_CATEGORY_CODE', '0000')

# Payment methods customers can choose (see checkout/providers.py), comma-separated
PAYMENT_METHODS = [m.strip() for m in os.environ.get('PAYMENT_METHODS', 'paynow').split(',') if m.strip()]
# An unpaid order's ingredients stay held while its payment is open. Each method sets how long
# that is; a payment gateway's own session expiry should match its entry here.
PAYMENT_HOLD_MINUTES = {
    'default': int(os.environ.get('PAYMENT_HOLD_MINUTES', '10')),
    'paynow': int(os.environ.get('PAYNOW_HOLD_MINUTES', '10')),
}
# time to start paying after placing the order, or to try another method after one fails
PAYMENT_START_GRACE_MINUTES = int(os.environ.get('PAYMENT_START_GRACE_MINUTES', '2'))
# an order never holds stock longer than this, however many payments it starts
ORDER_MAX_HOLD_MINUTES = int(os.environ.get('ORDER_MAX_HOLD_MINUTES', '30'))

REST_FRAMEWORK = {
    # staff-only unless a view says otherwise; the kiosk's public endpoints opt out explicitly
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAdminUser'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # pickup PIN attempts per machine (by IP), so 6-digit PINs can't be guessed
    'DEFAULT_THROTTLE_RATES': {'pickup': os.environ.get('PICKUP_ATTEMPTS_PER_MINUTE', '10') + '/min'},
}

# API contract: served at /api/schema/ (browse it at /api/docs/) and committed as openapi.yaml
SPECTACULAR_SETTINGS = {
    'TITLE': 'Drink Shop Kiosk API',
    'DESCRIPTION': (
        'Backend for the self-order kiosk and the mobile ordering app: menu, stock, orders and '
        'PayNow payment.\n\n'
        'Base URL: `http://localhost:8000` in development. The kiosk UI and the mobile app in a '
        'browser reach it through their dev-server proxy at `/api`. A phone on the same Wi-Fi uses '
        '`http://<computer IP>:8000`: start the backend with `./dev.sh --lan`, which listens on the '
        'network and adds that address to `DJANGO_ALLOWED_HOSTS`.\n\n'
        'Ordering endpoints are public. Everything else needs a staff login (session or HTTP Basic).'
    ),
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    # separate request and response shapes, so read-only fields like an order's id aren't asked for
    'COMPONENT_SPLIT_REQUEST': True,
    # sugar and ice share the same 0-4 level choices
    'ENUM_NAME_OVERRIDES': {'LevelEnum': 'ordering.models.OrderItem.Level'},
}
